python-interpreter-path = ".venv/Scripts/python.exe"

search-path = [
    ".",
    "src",
    "training",
    ".venv/Lib/site-packages",
    "C:/Users/Vignan Lara/AppData/Roaming/Python/Python310/site-packages",
]
site-package-path = [
    ".venv/Lib/site-packages",
    "C:/Users/Vignan Lara/AppData/Roaming/Python/Python310/site-packages",
]
project-excludes = [
    ".venv/**",
    "**/__pyrefly_virtual__/**",
    "D:/__pyrefly_virtual__/**",
    "**/inmemory/**",
    "**/__pycache__/**",
]
