"""Xeren Core Planning Integration Boundary.

Defines the stable interface between Xeren Core (and future trained models)
and the Autonomous Work Agent, providing structured task plans, pre-execution
validation, model adapter boundaries, and bounded error recovery.
"""

from abc import ABC, abstractmethod
import asyncio
import json
import logging
import time
from typing import Any, Dict, List, Optional, Set, Union
import uuid
from pydantic import BaseModel, Field, ValidationError

from xeren.agent.planner import Planner
from xeren.agent.types import ActionCategory, AgentAction, AgentState
from xeren.models.base import BaseLLM
from xeren.models.errors import OutputParsingError
from xeren.models.types import ChatMessage
from xeren.plugins.contract import PluginCapability
from xeren.plugins.manager import PluginManager

logger = logging.getLogger("xeren.core.planner")


# =============================================================================
# 1. Structured Plan Data Models
# =============================================================================

class PlanStep(BaseModel):
    """A single structured, validated step within a TaskPlan."""

    step_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique step identifier")
    description: str = Field(..., description="Human-readable step objective")
    action_type: str = Field(default="plugin", description="Action type: browser action name, plugin name, or 'plugin'")
    plugin_name: Optional[str] = Field(default=None, description="Target plugin if this step dispatches to a plugin")
    capability: Optional[str] = Field(default=None, description="Required plugin or tool capability")
    target: Optional[str] = Field(default=None, description="Action target (e.g. URL, selector, file, or topic)")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Action input arguments and payloads")
    consequential: bool = Field(default=False, description="Whether action requires safety/permission checks")
    category: ActionCategory = Field(default=ActionCategory.INTERACTIVE, description="Risk classification")
    expected_outcome: Optional[str] = Field(default=None, description="Expected condition or outcome to verify")


class TaskPlan(BaseModel):
    """Validated structured plan generated by Xeren Core for autonomous execution."""

    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Plan identifier")
    goal: str = Field(..., description="Top-level user goal or prompt")
    steps: List[PlanStep] = Field(..., min_length=1, description="Ordered sequence of plan steps")
    context: Dict[str, Any] = Field(default_factory=dict, description="Task context and parameters")
    estimated_complexity: str = Field(default="standard", description="Estimated plan complexity level")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Diagnostic and planning metadata")

    def __contains__(self, key: Any) -> bool:
        return key in self.__dict__ or hasattr(self, str(key))

    def __getitem__(self, key: str) -> Any:
        if hasattr(self, key):
            return getattr(self, key)
        raise KeyError(key)


class PlanContext(BaseModel):
    """Structured context passed into Core Planner for plan generation."""

    goal: str = Field(..., description="User goal or task description")
    task_context: Dict[str, Any] = Field(default_factory=dict, description="Relevant task context and variables")
    available_plugins: List[str] = Field(default_factory=list, description="Names of available registered plugins")
    available_capabilities: List[str] = Field(default_factory=list, description="List of available plugin/tool capabilities")
    constraints: List[str] = Field(default_factory=list, description="Operational constraints")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Environment and session metadata")


# =============================================================================
# 2. Planning Exceptions Hierarchy
# =============================================================================

class PlanningError(Exception):
    """Base exception for all core planning failures."""

    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None) -> None:
        super().__init__(message)
        self.message = message
        self.details = details or {}


class PlanValidationError(PlanningError):
    """Raised when a generated or input plan fails schema or safety validation."""
    pass


class UnsupportedPluginError(PlanValidationError):
    """Raised when a plan references a plugin that is not registered."""
    pass


class UnsupportedCapabilityError(PlanValidationError):
    """Raised when a plan requests a capability not supported by available plugins."""
    pass


class MissingArgumentError(PlanValidationError):
    """Raised when a plan step is missing mandatory parameters."""
    pass


class UnsafePlanError(PlanValidationError):
    """Raised when a plan contains prohibited or unsafe execution requests."""
    pass


class ModelInferenceError(PlanningError):
    """Raised when the planning model fails to produce an inference response."""
    pass


class PlannerTimeoutError(PlanningError):
    """Raised when model plan generation exceeds allowable time limit after retries."""
    pass


# =============================================================================
# 3. Plan Validation Engine
# =============================================================================

class PlanValidator:
    """Pre-execution validation engine enforcing schema, plugin, capability, and safety rules."""

    KNOWN_BROWSER_ACTIONS: Set[str] = {
        "navigate",
        "observe",
        "click",
        "type",
        "select",
        "scroll",
        "extract",
        "upload",
        "download",
        "close",
    }

    CONSEQUENTIAL_ACTIONS: Set[str] = {
        "upload",
        "download",
        "delete",
        "submit",
        "purchase",
        "system_command",
    }

    UNSAFE_PATTERNS: List[str] = [
        "rm -rf",
        ":(){ :|:& };:",
        "format c:",
        "curl | bash",
        "wget | bash",
        "eval(",
        "__import__(",
    ]

    def __init__(self, plugin_manager: Optional[PluginManager] = None) -> None:
        self.plugin_manager = plugin_manager

    def validate(self, plan: TaskPlan) -> None:
        """Validate a TaskPlan before execution. Raises PlanValidationError on failure."""
        if not plan.goal or not plan.goal.strip():
            raise PlanValidationError("TaskPlan must specify a non-empty user goal.")

        if not plan.steps:
            raise PlanValidationError("TaskPlan must contain at least one step.")

        for idx, step in enumerate(plan.steps):
            self._validate_step(step, idx)

    def _validate_step(self, step: PlanStep, index: int) -> None:
        """Validate an individual PlanStep."""
        if not step.description or not step.description.strip():
            raise PlanValidationError(
                f"Step {index + 1} has an empty description.",
                details={"step_id": step.step_id, "index": index},
            )

        action_type = step.action_type.lower()
        target_plugin = step.plugin_name.lower() if step.plugin_name else None

        # 1. Check for unsafe/malicious command patterns in parameters or target
        self._check_safety(step, index)

        # 2. Auto-tag consequential steps
        if action_type in self.CONSEQUENTIAL_ACTIONS or (target_plugin and target_plugin in self.CONSEQUENTIAL_ACTIONS):
            step.consequential = True
            step.category = ActionCategory.CONSEQUENTIAL

        # 3. Resolve whether action is a Browser action or a Plugin action
        is_browser = action_type in self.KNOWN_BROWSER_ACTIONS

        if is_browser:
            self._validate_browser_parameters(step, index)
            return

        # 4. If action is a plugin action or references a plugin
        resolved_plugin = target_plugin or (action_type if action_type != "plugin" else None)

        if self.plugin_manager is not None and resolved_plugin:
            # Check if plugin is registered
            if not self.plugin_manager.has(resolved_plugin):
                available = self.plugin_manager.list_names()
                raise UnsupportedPluginError(
                    f"Step {index + 1} references unsupported plugin '{resolved_plugin}'. Available plugins: {available}",
                    details={"step_id": step.step_id, "plugin_name": resolved_plugin, "available": available},
                )

            plugin_instance = self.plugin_manager.get(resolved_plugin)
            if plugin_instance:
                # Check capability if specified
                if step.capability:
                    cap_str = step.capability if isinstance(step.capability, str) else step.capability.value
                    if cap_str not in plugin_instance.capabilities:
                        raise UnsupportedCapabilityError(
                            f"Plugin '{resolved_plugin}' does not support required capability '{cap_str}'. Supported: {plugin_instance.capabilities}",
                            details={"plugin": resolved_plugin, "required": cap_str, "supported": plugin_instance.capabilities},
                        )

            self._validate_plugin_parameters(step, resolved_plugin, index)
        elif self.plugin_manager is None and resolved_plugin:
            # No plugin manager attached; validate generic parameters
            self._validate_plugin_parameters(step, resolved_plugin, index)
        elif not is_browser and not resolved_plugin:
            raise PlanValidationError(
                f"Step {index + 1} specifies unknown action type '{action_type}' with no target plugin.",
                details={"step_id": step.step_id, "action_type": action_type},
            )

    def _check_safety(self, step: PlanStep, index: int) -> None:
        """Scan step parameters and target for dangerous arbitrary execution patterns."""
        combined_text = f"{step.target or ''} {json.dumps(step.parameters, default=str)}"
        for pattern in self.UNSAFE_PATTERNS:
            if pattern in combined_text:
                raise UnsafePlanError(
                    f"Step {index + 1} contains prohibited execution pattern '{pattern}'. Arbitrary code execution is blocked.",
                    details={"step_id": step.step_id, "pattern": pattern},
                )

    def _validate_browser_parameters(self, step: PlanStep, index: int) -> None:
        """Verify mandatory parameters for browser actions."""
        action = step.action_type.lower()
        if action == "navigate":
            url = step.target or step.parameters.get("url")
            if not url or not str(url).strip():
                raise MissingArgumentError(
                    f"Step {index + 1} (navigate) is missing mandatory 'url' parameter.",
                    details={"step_id": step.step_id, "action": action},
                )
        elif action == "type":
            text = step.parameters.get("text")
            selector = step.target or step.parameters.get("selector")
            if text is None:
                raise MissingArgumentError(
                    f"Step {index + 1} (type) is missing mandatory 'text' parameter.",
                    details={"step_id": step.step_id, "action": action},
                )
            if not selector:
                raise MissingArgumentError(
                    f"Step {index + 1} (type) is missing target selector.",
                    details={"step_id": step.step_id, "action": action},
                )
        elif action == "click":
            selector = step.target or step.parameters.get("selector")
            if not selector:
                raise MissingArgumentError(
                    f"Step {index + 1} (click) is missing target selector.",
                    details={"step_id": step.step_id, "action": action},
                )
        elif action == "upload":
            file_path = step.parameters.get("file_path")
            if not file_path:
                raise MissingArgumentError(
                    f"Step {index + 1} (upload) is missing mandatory 'file_path' parameter.",
                    details={"step_id": step.step_id, "action": action},
                )

    def _validate_plugin_parameters(self, step: PlanStep, plugin_name: str, index: int) -> None:
        """Verify standard parameters for known plugin types."""
        params = step.parameters

        if plugin_name == "research":
            query = params.get("query") or step.target
            if not query:
                raise MissingArgumentError(
                    f"Step {index + 1} (research) is missing mandatory 'query' parameter.",
                    details={"step_id": step.step_id, "plugin": plugin_name},
                )
        elif plugin_name in {"coding", "data", "website"}:
            op = params.get("operation")
            if not op:
                raise MissingArgumentError(
                    f"Step {index + 1} ({plugin_name}) is missing mandatory 'operation' parameter.",
                    details={"step_id": step.step_id, "plugin": plugin_name},
                )


# =============================================================================
# 4. Model Adapter Boundary
# =============================================================================

class BaseCoreModelAdapter(ABC):
    """Abstract interface decoupling raw model loading/inference from planner orchestration."""

    @abstractmethod
    def infer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        """Synchronously produce raw structured plan dictionary from model."""
        pass

    @abstractmethod
    async def ainfer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        """Asynchronously produce raw structured plan dictionary from model."""
        pass


class LLMCoreModelAdapter(BaseCoreModelAdapter):
    """Adapter wrapping any BaseLLM provider for structured TaskPlan inference."""

    def __init__(
        self,
        llm: BaseLLM,
        timeout_seconds: float = 30.0,
        enable_fallback: bool = True,
    ) -> None:
        self.llm = llm
        self.timeout_seconds = timeout_seconds
        self.enable_fallback = enable_fallback
        self._fallback_adapter = DeterministicCoreModelAdapter()

    def _build_prompt(self, plan_context: PlanContext) -> List[ChatMessage]:
        plugins_desc = ", ".join(plan_context.available_plugins) if plan_context.available_plugins else "browser"
        caps_desc = ", ".join(plan_context.available_capabilities) if plan_context.available_capabilities else "standard"
        system_msg = (
            "You are the Xeren Core Planner. Decompose the user goal into a strict JSON TaskPlan.\n"
            f"Available plugins: {plugins_desc}\n"
            f"Available capabilities: {caps_desc}\n"
            "Respond strictly with valid JSON conforming to the TaskPlan schema without commentary."
        )
        user_msg = f"Goal: {plan_context.goal}\nContext: {json.dumps(plan_context.task_context, default=str)}"
        return [ChatMessage.system(system_msg), ChatMessage.user(user_msg)]

    def infer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        messages = self._build_prompt(plan_context)
        try:
            res = self.llm.generate_structured(messages, TaskPlan)
            return res.model_dump()
        except (ValidationError, OutputParsingError, json.JSONDecodeError) as err:
            if self.enable_fallback:
                logger.warning("Model produced malformed JSON for TaskPlan. Engaging safe recovery fallback: %s", err)
                return self._fallback_adapter.infer_plan(plan_context)
            raise PlanValidationError(f"Model output failed schema validation: {err}", details={"errors": str(err)}) from err
        except Exception as err:
            if self.enable_fallback:
                logger.warning("Model inference failed. Engaging safe recovery fallback: %s", err)
                return self._fallback_adapter.infer_plan(plan_context)
            raise ModelInferenceError(f"Model inference failed: {err}", details={"raw_error": str(err)}) from err

    async def ainfer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        messages = self._build_prompt(plan_context)
        try:
            res = await self.llm.agenerate_structured(messages, TaskPlan)
            return res.model_dump()
        except (ValidationError, OutputParsingError, json.JSONDecodeError) as err:
            if self.enable_fallback:
                logger.warning("Model produced malformed JSON for TaskPlan. Engaging safe recovery fallback: %s", err)
                return await self._fallback_adapter.ainfer_plan(plan_context)
            raise PlanValidationError(f"Model output failed schema validation: {err}", details={"errors": str(err)}) from err
        except Exception as err:
            if self.enable_fallback:
                logger.warning("Model inference failed. Engaging safe recovery fallback: %s", err)
                return await self._fallback_adapter.ainfer_plan(plan_context)
            raise ModelInferenceError(f"Model inference failed: {err}", details={"raw_error": str(err)}) from err


class DeterministicCoreModelAdapter(BaseCoreModelAdapter):
    """Deterministic rule-based model adapter for testing and offline execution."""

    def __init__(self, canned_plan: Optional[Dict[str, Any]] = None) -> None:
        self.canned_plan = canned_plan

    def _generate_rule_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        if self.canned_plan is not None:
            return dict(self.canned_plan)

        goal_lower = plan_context.goal.lower()
        steps: List[Dict[str, Any]] = []

        if "multi" in goal_lower or ("research" in goal_lower and "code" in goal_lower):
            steps = [
                {
                    "description": f"Research background for: {plan_context.goal}",
                    "action_type": "research",
                    "plugin_name": "research",
                    "capability": PluginCapability.WEB_SEARCH.value,
                    "parameters": {"query": plan_context.goal, "depth": "overview"},
                },
                {
                    "description": f"Generate code implementation for: {plan_context.goal}",
                    "action_type": "coding",
                    "plugin_name": "coding",
                    "capability": PluginCapability.CODE_GENERATION.value,
                    "parameters": {"operation": "generate", "task": plan_context.goal},
                },
            ]
        elif "research" in goal_lower or "search" in goal_lower:
            steps = [
                {
                    "description": f"Research topic: {plan_context.goal}",
                    "action_type": "research",
                    "plugin_name": "research",
                    "capability": PluginCapability.WEB_SEARCH.value,
                    "target": plan_context.goal,
                    "parameters": {"query": plan_context.goal, "depth": "standard"},
                },
                {
                    "description": f"Synthesize research findings for {plan_context.goal}",
                    "action_type": "research",
                    "plugin_name": "research",
                    "capability": PluginCapability.SYNTHESIS.value,
                    "target": plan_context.goal,
                    "parameters": {"query": plan_context.goal, "depth": "standard"},
                },
            ]
        elif "code" in goal_lower or "script" in goal_lower:
            steps = [
                {
                    "description": f"Generate code for: {plan_context.goal}",
                    "action_type": "coding",
                    "plugin_name": "coding",
                    "capability": PluginCapability.CODE_GENERATION.value,
                    "parameters": {"operation": "generate", "task": plan_context.goal},
                },
                {
                    "description": "Verify generated code syntax",
                    "action_type": "coding",
                    "plugin_name": "coding",
                    "capability": PluginCapability.CODE_VERIFICATION.value,
                    "parameters": {"operation": "verify", "task": plan_context.goal},
                },
            ]
        elif "data" in goal_lower or "dataset" in goal_lower:
            records_val = plan_context.task_context.get("records") or plan_context.task_context.get("data")
            if not records_val and not plan_context.task_context.get("file_path"):
                records_val = [{"metric": "default", "value": 1}]
            steps = [
                {
                    "description": f"Inspect dataset for: {plan_context.goal}",
                    "action_type": "data",
                    "plugin_name": "data",
                    "capability": PluginCapability.DATA_ANALYSIS.value,
                    "parameters": {
                        "operation": "inspect",
                        "records": records_val,
                        "file_path": plan_context.task_context.get("file_path"),
                    },
                }
            ]
        elif "website" in goal_lower or "landing page" in goal_lower:
            steps = [
                {
                    "description": f"Generate website for: {plan_context.goal}",
                    "action_type": "website",
                    "plugin_name": "website",
                    "capability": PluginCapability.WEBSITE_GENERATION.value,
                    "parameters": {"requirement": plan_context.goal, "operation": "generate"},
                },
            ]
        elif "browse" in goal_lower or "navigate" in goal_lower or "http" in goal_lower or "browser" in goal_lower:
            url = plan_context.task_context.get("url", "https://example.com")
            steps = [
                {
                    "description": f"Navigate to {url}",
                    "action_type": "navigate",
                    "target": url,
                    "parameters": {"url": url},
                },
                {
                    "description": "Observe page structure and content",
                    "action_type": "observe",
                    "category": ActionCategory.READ_ONLY.value,
                },
                {
                    "description": "Extract target content from page",
                    "action_type": "extract",
                    "parameters": {"extract_type": "text"},
                    "category": ActionCategory.READ_ONLY.value,
                },
            ]
        elif "knowledge" in goal_lower or "rag" in goal_lower or "document" in goal_lower or "question" in goal_lower:
            steps = [
                {
                    "description": f"Retrieve knowledge for: {plan_context.goal}",
                    "action_type": "knowledge",
                    "plugin_name": "knowledge",
                    "capability": PluginCapability.KNOWLEDGE_RETRIEVAL.value,
                    "parameters": {"query": plan_context.goal, "operation": "query"},
                }
            ]
        elif "download" in goal_lower:
            steps = [
                {
                    "description": "Navigate to download target",
                    "action_type": "navigate",
                    "target": plan_context.task_context.get("url", "https://example.com/download"),
                    "parameters": {"url": plan_context.task_context.get("url", "https://example.com/download")},
                },
                {
                    "description": "Trigger download of target file",
                    "action_type": "download",
                    "target": "#download-btn",
                    "parameters": {"trigger_selector": "#download-btn"},
                    "consequential": True,
                    "category": ActionCategory.CONSEQUENTIAL.value,
                },
            ]
        elif "upload" in goal_lower:
            steps = [
                {
                    "description": "Navigate to upload target",
                    "action_type": "navigate",
                    "target": plan_context.task_context.get("url", "https://example.com/upload"),
                    "parameters": {"url": plan_context.task_context.get("url", "https://example.com/upload")},
                },
                {
                    "description": "Upload file to designated form input",
                    "action_type": "upload",
                    "target": "input[type='file']",
                    "parameters": {
                        "selector": "input[type='file']",
                        "file_path": plan_context.task_context.get("file_path", "data.csv"),
                    },
                    "consequential": True,
                    "category": ActionCategory.CONSEQUENTIAL.value,
                },
            ]
        else:
            # Default browser exploration steps
            url = plan_context.task_context.get("url", "https://example.com")
            steps = [
                {
                    "description": f"Navigate to {url}",
                    "action_type": "navigate",
                    "target": url,
                    "parameters": {"url": url},
                },
                {
                    "description": "Observe page structure and content",
                    "action_type": "observe",
                    "category": ActionCategory.READ_ONLY.value,
                },
                {
                    "description": "Extract target content from page",
                    "action_type": "extract",
                    "parameters": {"extract_type": "text"},
                    "category": ActionCategory.READ_ONLY.value,
                },
            ]

        return {
            "plan_id": str(uuid.uuid4()),
            "goal": plan_context.goal,
            "steps": steps,
            "context": plan_context.task_context,
            "estimated_complexity": "standard",
            "metadata": {"source": "deterministic_rules"},
        }

    def infer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        return self._generate_rule_plan(plan_context)

    async def ainfer_plan(self, plan_context: PlanContext) -> Dict[str, Any]:
        return self._generate_rule_plan(plan_context)


# =============================================================================
# 5. Stable CorePlanner Interface and Adapter
# =============================================================================

class BaseCorePlanner(ABC):
    """Stable interface through which Xeren Core provides plans to the Autonomous Agent."""

    @abstractmethod
    def create_task_plan(self, goal: str, context: Optional[Dict[str, Any]] = None) -> TaskPlan:
        """Synchronously create and validate a structured TaskPlan from user goal and context."""
        pass

    @abstractmethod
    async def acreate_task_plan(self, goal: str, context: Optional[Dict[str, Any]] = None) -> TaskPlan:
        """Asynchronously create and validate a structured TaskPlan from user goal and context."""
        pass


class CorePlannerAdapter(Planner, BaseCorePlanner):
    """Production planner adapter connecting Xeren Core models to AgentController.

    Features:
    - Decoupled model inference via BaseCoreModelAdapter.
    - Pre-execution validation via PlanValidator.
    - Bounded retries and timeout protection.
    - Duck-typed compatibility with AgentController (create_plan, next_action, replan).
    """

    def __init__(
        self,
        model_adapter: Optional[BaseCoreModelAdapter] = None,
        llm: Optional[BaseLLM] = None,
        plugin_manager: Optional[PluginManager] = None,
        max_retries: int = 2,
        timeout_seconds: float = 10.0,
        enable_fallback: bool = True,
    ) -> None:
        super().__init__(llm=llm)
        self.plugin_manager = plugin_manager
        self.validator = PlanValidator(plugin_manager=plugin_manager)
        self.max_retries = max_retries
        self.timeout_seconds = timeout_seconds
        self.enable_fallback = enable_fallback

        # Configure model adapter
        if model_adapter is not None:
            self.model_adapter = model_adapter
        elif llm is not None:
            self.model_adapter = LLMCoreModelAdapter(
                llm=llm, timeout_seconds=timeout_seconds, enable_fallback=enable_fallback
            )
        else:
            self.model_adapter = DeterministicCoreModelAdapter()

        # Cache active TaskPlans indexed by session or task
        self._active_plans: Dict[str, TaskPlan] = {}

    def _build_context(self, goal: str, context: Optional[Dict[str, Any]] = None) -> PlanContext:
        ctx = context or {}
        available_plugins = self.plugin_manager.list_names() if self.plugin_manager else []
        available_caps: List[str] = []
        if self.plugin_manager:
            for p in self.plugin_manager.list_plugins():
                available_caps.extend(p.capabilities)

        return PlanContext(
            goal=goal,
            task_context=ctx,
            available_plugins=available_plugins,
            available_capabilities=list(set(available_caps)),
            constraints=ctx.get("constraints", []),
            metadata=ctx.get("metadata", {}),
        )

    def create_task_plan(self, goal: str, context: Optional[Dict[str, Any]] = None) -> TaskPlan:
        """Synchronously create and validate TaskPlan with bounded retries."""
        plan_context = self._build_context(goal, context)
        last_error: Optional[Exception] = None

        for attempt in range(self.max_retries + 1):
            try:
                raw_plan = self.model_adapter.infer_plan(plan_context)
                if not isinstance(raw_plan, dict):
                    raise PlanValidationError("Model failed to output a structured dictionary plan.")

                task_plan = TaskPlan.model_validate(raw_plan)
                self.validator.validate(task_plan)
                return task_plan

            except (UnsupportedPluginError, UnsupportedCapabilityError, MissingArgumentError, UnsafePlanError):
                # Don't retry structural or safety rejection errors
                raise
            except (PlanValidationError, ModelInferenceError, Exception) as err:
                last_error = err
                logger.warning("Plan generation attempt %d failed: %s", attempt + 1, err)
                if attempt == self.max_retries:
                    break

        if isinstance(last_error, PlanningError):
            raise last_error
        raise ModelInferenceError(f"Planning failed after {self.max_retries + 1} attempts: {last_error}")

    async def acreate_task_plan(self, goal: str, context: Optional[Dict[str, Any]] = None) -> TaskPlan:
        """Asynchronously create and validate TaskPlan with timeout and bounded retries."""
        plan_context = self._build_context(goal, context)
        last_error: Optional[Exception] = None

        for attempt in range(self.max_retries + 1):
            try:
                coro = self.model_adapter.ainfer_plan(plan_context)
                raw_plan = await asyncio.wait_for(coro, timeout=self.timeout_seconds)

                if not isinstance(raw_plan, dict):
                    raise PlanValidationError("Model failed to output a structured dictionary plan.")

                task_plan = TaskPlan.model_validate(raw_plan)
                self.validator.validate(task_plan)
                return task_plan

            except asyncio.TimeoutError as err:
                last_error = err
                logger.warning("Plan generation attempt %d timed out after %.2fs", attempt + 1, self.timeout_seconds)
                if attempt == self.max_retries:
                    raise PlannerTimeoutError(
                        f"Model plan generation timed out after {self.max_retries + 1} attempts.",
                        details={"timeout_seconds": self.timeout_seconds, "attempts": self.max_retries + 1},
                    ) from err
            except (UnsupportedPluginError, UnsupportedCapabilityError, MissingArgumentError, UnsafePlanError):
                # Don't retry deterministic safety or capability errors
                raise
            except (PlanValidationError, ModelInferenceError, Exception) as err:
                last_error = err
                logger.warning("Plan generation attempt %d failed: %s", attempt + 1, err)
                if attempt == self.max_retries:
                    break

        if isinstance(last_error, PlanningError):
            raise last_error
        raise ModelInferenceError(f"Planning failed after {self.max_retries + 1} attempts: {last_error}")

    # -------------------------------------------------------------------------
    # Duck-typed methods for seamless AgentController integration
    # -------------------------------------------------------------------------

    def create_plan(self, task: str, context: Optional[Dict[str, Any]] = None) -> List[str]:
        """Produce step description strings for AgentController, caching the TaskPlan."""
        if context and "task_plan" in context and isinstance(context["task_plan"], TaskPlan):
            task_plan = context["task_plan"]
        else:
            task_plan = self.create_task_plan(task, context)
        key = context.get("session_id", task) if context else task
        self._active_plans[key] = task_plan
        return [step.description for step in task_plan.steps]

    def next_action(self, state: AgentState) -> Optional[AgentAction]:
        """Convert the next PlanStep in the active TaskPlan into an executable AgentAction."""
        key = state.session_id or state.task
        task_plan = self._active_plans.get(key)

        if task_plan is None:
            # Generate TaskPlan if not already present
            task_plan = self.create_task_plan(state.task, state.memory)
            self._active_plans[key] = task_plan
            state.plan = [step.description for step in task_plan.steps]

        state.task_plan = task_plan

        if state.step_count >= len(task_plan.steps):
            return None  # All steps executed

        current_step_model = task_plan.steps[state.step_count]
        state.current_step = current_step_model.description

        # Map PlanStep into AgentAction
        action = AgentAction(
            action_id=current_step_model.step_id,
            action_type=current_step_model.action_type,
            target=current_step_model.target,
            parameters=dict(current_step_model.parameters),
            consequential=current_step_model.consequential,
            category=current_step_model.category,
            description=current_step_model.description,
        )

        # Attach plugin_name if defined
        if current_step_model.plugin_name:
            action.parameters["plugin_name"] = current_step_model.plugin_name
        if current_step_model.capability:
            action.parameters["capability"] = current_step_model.capability

        return action

    def replan(self, state: AgentState, failure_reason: str) -> List[str]:
        """Adapt active plan in response to a failed step."""
        logger.info("CorePlannerAdapter replanning due to: %s", failure_reason)
        key = getattr(state, "session_id", getattr(state, "task_id", getattr(state, "task", getattr(state, "goal", "default"))))
        active_plan = self._active_plans.get(key)

        revised_steps: List[PlanStep] = []
        if active_plan:
            # Preserve completed steps
            for i in range(min(state.step_count, len(active_plan.steps))):
                revised_steps.append(active_plan.steps[i])

        # Inject diagnostic and recovery step
        diag_step = PlanStep(
            step_id=str(uuid.uuid4()),
            description=f"Inspect state after failure: {failure_reason}",
            action_type="observe",
            category=ActionCategory.READ_ONLY,
        )
        revised_steps.append(diag_step)

        # Update cached plan
        if active_plan:
            active_plan.steps = revised_steps
            state.plan = [s.description for s in revised_steps]
        else:
            state.plan.append(diag_step.description)

        return state.plan

    async def areplan(
        self,
        failed_step: Optional[PlanStep] = None,
        error_message: str = "",
        context: Optional[Dict[str, Any]] = None,
        state: Optional[AgentState] = None,
        **kwargs: Any,
    ) -> Any:
        """Asynchronously replan, supporting both TaskPlan and AgentState formats."""
        if state is not None:
            return self.replan(state, error_message or kwargs.get("failure_reason", "Step execution failed"))

        # Replan from PlanStep
        err_msg = error_message or kwargs.get("failure_reason", "Step execution failed")
        step_id = failed_step.step_id if failed_step else str(uuid.uuid4())
        desc = f"Recover from failure in {failed_step.description if failed_step else 'step'}: {err_msg}"
        diag_step = PlanStep(
            step_id=str(uuid.uuid4()),
            description=desc,
            action_type="observe",
            category=ActionCategory.READ_ONLY,
        )
        return TaskPlan(
            plan_id=str(uuid.uuid4()),
            goal=f"Recover: {err_msg}",
            steps=[diag_step],
            context=context or {},
            metadata={"replan_source_step": step_id},
        )


__all__ = [
    "PlanStep",
    "TaskPlan",
    "PlanContext",
    "PlanningError",
    "PlanValidationError",
    "UnsupportedPluginError",
    "UnsupportedCapabilityError",
    "MissingArgumentError",
    "UnsafePlanError",
    "ModelInferenceError",
    "PlannerTimeoutError",
    "PlanValidator",
    "BaseCoreModelAdapter",
    "LLMCoreModelAdapter",
    "DeterministicCoreModelAdapter",
    "BaseCorePlanner",
    "CorePlannerAdapter",
]
