"""End-to-end data processing pipeline for Xeren model training.

Orchestrates:
Raw Experience -> Validation -> Contradiction Check -> Quality Filtering ->
Deduplication -> Split Partitioning -> Formatting -> Export & Manifest
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
from pydantic import BaseModel, Field

from xeren.data.dataset import ExperienceDataset, load_jsonl_dataset
from xeren.data.formatter import (
    DPOExample,
    ExperienceFormatter,
    SFTChatExample,
    StructuredAgentExample,
)
from xeren.data.schema import DatasetSplit, ExperienceRecord
from xeren.data.validator import DatasetValidator, ValidationResult


class PipelineManifest(BaseModel):
    """Manifest summary generated by the training data pipeline."""
    total_input_records: int
    valid_records: int
    malformed_records: int
    duplicate_records: int
    rejected_contradictions: int
    training_eligible_records: int
    splits: Dict[str, int] = Field(default_factory=dict)
    sft_examples_exported: int = 0
    dpo_pairs_exported: int = 0
    structured_examples_exported: int = 0
    output_files: Dict[str, str] = Field(default_factory=dict)
    statistics: Dict[str, Any] = Field(default_factory=dict)


class TrainingDataPipeline:
    """Orchestrates ingestion, curation, deduplication, formatting, and export of training datasets."""

    def __init__(
        self,
        validator: Optional[DatasetValidator] = None,
        formatter: Optional[ExperienceFormatter] = None,
        min_quality_score: float = 0.7,
        require_verified: bool = True,
        allow_failures: bool = False,
    ) -> None:
        self.validator = validator or DatasetValidator(
            require_verified=require_verified,
            min_quality_score=min_quality_score,
        )
        self.formatter = formatter or ExperienceFormatter()
        self.min_quality_score = min_quality_score
        self.require_verified = require_verified
        self.allow_failures = allow_failures

    def process_records(
        self,
        raw_records: List[ExperienceRecord],
    ) -> Tuple[ExperienceDataset, ValidationResult]:
        """Validate, deduplicate, and curate a collection of raw experience records."""
        # 1. Validation & sanitization
        val_result = self.validator.validate_dataset(raw_records)

        # 2. Build dataset with valid records
        clean_dataset = ExperienceDataset()
        for rec in raw_records:
            sanitized = self.validator.preprocess_record(rec)
            is_valid, _ = self.validator.validate_record(sanitized)
            if is_valid:
                try:
                    clean_dataset.add(sanitized, prevent_duplicates=True)
                except ValueError:
                    # Duplicate caught during insertion
                    pass

        return clean_dataset, val_result

    def export_training_artifacts(
        self,
        dataset: ExperienceDataset,
        output_dir: Union[str, Path],
        export_sft: bool = True,
        export_dpo: bool = True,
        export_structured: bool = True,
    ) -> PipelineManifest:
        """Filter eligible training data, format into training targets, and write to disk."""
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        stats = dataset.summary_stats()
        eligible_dataset = dataset.filter_for_training(
            min_quality_score=self.min_quality_score,
            require_verified=self.require_verified,
            allow_failures=self.allow_failures,
        )

        manifest = PipelineManifest(
            total_input_records=len(dataset),
            valid_records=len(dataset),
            malformed_records=0,
            duplicate_records=0,
            rejected_contradictions=0,
            training_eligible_records=len(eligible_dataset),
            splits=stats.get("splits", {}),
            statistics=stats,
        )

        # Export raw filtered experience JSONL by split
        for split_enum in DatasetSplit:
            split_records = [r for r in eligible_dataset.records if r.split == split_enum]
            if split_records:
                split_file = out_path / f"{split_enum.value}.jsonl"
                with split_file.open("w", encoding="utf-8") as f:
                    for r in split_records:
                        f.write(r.model_dump_json() + "\n")
                manifest.output_files[f"experience_{split_enum.value}"] = str(split_file)

        # Export SFT ChatML JSONL
        if export_sft:
            sft_file = out_path / "sft_chat.jsonl"
            sft_examples = self.formatter.format_dataset_for_sft(eligible_dataset)
            with sft_file.open("w", encoding="utf-8") as f:
                for ex in sft_examples:
                    f.write(json.dumps(ex.to_dict()) + "\n")
            manifest.sft_examples_exported = len(sft_examples)
            manifest.output_files["sft_chat"] = str(sft_file)

        # Export DPO Preference JSONL
        if export_dpo:
            dpo_file = out_path / "dpo_pairs.jsonl"
            dpo_examples = self.formatter.format_dataset_for_dpo(dataset)
            with dpo_file.open("w", encoding="utf-8") as f:
                for dpo_ex in dpo_examples:
                    f.write(json.dumps(dpo_ex.to_dict()) + "\n")
            manifest.dpo_pairs_exported = len(dpo_examples)
            manifest.output_files["dpo_pairs"] = str(dpo_file)

        # Export Structured Agent JSONL
        if export_structured:
            struct_file = out_path / "structured_agent.jsonl"
            struct_examples = self.formatter.format_dataset_for_structured_agent(eligible_dataset)
            with struct_file.open("w", encoding="utf-8") as f:
                for st_ex in struct_examples:
                    prompt, target = st_ex.to_formatted_prompt_and_target()
                    payload = {
                        "sample_id": st_ex.sample_id,
                        "prompt": prompt,
                        "target": target,
                        "final_quality_score": st_ex.final_quality_score,
                    }
                    f.write(json.dumps(payload) + "\n")
            manifest.structured_examples_exported = len(struct_examples)
            manifest.output_files["structured_agent"] = str(struct_file)

        # Save manifest
        manifest_file = out_path / "pipeline_manifest.json"
        with manifest_file.open("w", encoding="utf-8") as f:
            f.write(manifest.model_dump_json(indent=2))
        manifest.output_files["manifest"] = str(manifest_file)

        return manifest
