"""Core typed data structures for LLM messages, outputs, streaming, and usage."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class Role(str, Enum):
    """Chat message roles."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class FunctionCall(BaseModel):
    """Specification of a function call generated by an LLM."""
    name: str
    arguments: str


class ToolCall(BaseModel):
    """Specification of a tool call generated by an LLM."""
    id: str
    type: str = "function"
    function: FunctionCall


class ChatMessage(BaseModel):
    """A single chat message in a conversational context."""
    role: Role
    content: Optional[str] = None
    name: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @classmethod
    def system(cls, content: str, **kwargs: Any) -> "ChatMessage":
        """Create a system message."""
        return cls(role=Role.SYSTEM, content=content, **kwargs)

    @classmethod
    def user(cls, content: str, **kwargs: Any) -> "ChatMessage":
        """Create a user message."""
        return cls(role=Role.USER, content=content, **kwargs)

    @classmethod
    def assistant(
        cls,
        content: Optional[str] = None,
        tool_calls: Optional[List[ToolCall]] = None,
        **kwargs: Any,
    ) -> "ChatMessage":
        """Create an assistant message."""
        return cls(role=Role.ASSISTANT, content=content, tool_calls=tool_calls, **kwargs)

    @classmethod
    def tool(cls, content: str, tool_call_id: str, **kwargs: Any) -> "ChatMessage":
        """Create a tool result message."""
        return cls(role=Role.TOOL, content=content, tool_call_id=tool_call_id, **kwargs)


class TokenUsage(BaseModel):
    """Token consumption and accounting."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost: Optional[float] = None


class LLMResponse(BaseModel):
    """Complete response returned by an LLM provider."""
    content: str
    message: ChatMessage
    finish_reason: str = "stop"
    usage: TokenUsage = Field(default_factory=TokenUsage)
    model_id: str = ""
    raw_response: Dict[str, Any] = Field(default_factory=dict)


class StreamChunk(BaseModel):
    """A single incremental chunk yielded during streaming inference."""
    delta_content: str = ""
    delta_tool_calls: Optional[List[ToolCall]] = None
    finish_reason: Optional[str] = None
    usage: Optional[TokenUsage] = None
