"""Data schemas and contracts for Xeren Autonomous Workspace & File Intelligence.

Defines models for authorized workspace roots, task requirements, candidate discovery,
ranking, safe content retrieval, and structured workspace context.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional
import uuid

from pydantic import BaseModel, Field


class PermissionMode(str, Enum):
    """Supported filesystem permission modes for workspace roots."""

    READ_ONLY = "read_only"
    READ_WRITE = "read_write"


class FileCategory(str, Enum):
    """Categorization of workspace files for task-driven routing."""

    STRUCTURED_DATA = "structured_data"  # CSV, XLSX, Parquet, JSON datasets
    DOCUMENT = "document"                # PDF, DOCX, MD, TXT, RTF
    SOURCE_CODE = "source_code"          # Python, TypeScript, JavaScript, etc.
    CONFIG = "config"                    # YAML, TOML, INI, JSON config
    ARCHIVE = "archive"                  # ZIP, TAR, GZ
    BINARY = "binary"                    # Images, executables, compiled objects
    UNKNOWN = "unknown"


class WorkspaceRoot(BaseModel):
    """An explicitly authorized filesystem root directory."""

    root_id: str = Field(..., description="Unique identifier for the workspace root")
    path: Path = Field(..., description="Absolute, canonical filesystem path to root directory")
    permission_mode: PermissionMode = Field(
        default=PermissionMode.READ_ONLY,
        description="Allowed permission mode, strictly defaults to READ_ONLY",
    )
    enabled: bool = Field(default=True, description="Whether this root is currently active")
    allowed_operations: List[str] = Field(
        default_factory=lambda: ["read", "scan", "search"],
        description="List of allowed operations: read, scan, search, write, delete",
    )

    model_config = {"arbitrary_types_allowed": True}

    def can_read(self) -> bool:
        """Check if root allows reading."""
        return self.enabled and "read" in self.allowed_operations

    def can_write(self) -> bool:
        """Check if root allows writing (requires READ_WRITE mode and write in operations)."""
        return (
            self.enabled
            and self.permission_mode == PermissionMode.READ_WRITE
            and "write" in self.allowed_operations
        )


class ScannedFileMetadata(BaseModel):
    """Lightweight metadata discovered during initial scanning without loading full content."""

    file_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = Field(..., description="File or directory name")
    relative_path: str = Field(..., description="Path relative to the workspace root")
    absolute_path: Path = Field(..., description="Canonical path on filesystem")
    extension: str = Field(default="", description="Lowercased file extension with leading dot")
    size_bytes: int = Field(default=0, ge=0, description="File size in bytes")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp",
    )
    modified_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last modification timestamp",
    )
    mime_type: Optional[str] = Field(default=None, description="MIME type if detected")
    is_binary: bool = Field(default=False, description="Whether file is binary")
    is_directory: bool = Field(default=False, description="Whether entity is a directory")
    category: FileCategory = Field(default=FileCategory.UNKNOWN, description="Inferred file category")
    root_id: str = Field(default="default", description="Workspace root identifier")

    model_config = {"arbitrary_types_allowed": True}


class WorkspaceRequirement(BaseModel):
    """A structured requirement generated by Core/Planner identifying needed workspace resources."""

    requires_workspace: bool = Field(
        default=True,
        description="Whether the task requires discovering or accessing workspace files",
    )
    purpose: str = Field(
        ...,
        description="Identified purpose (e.g. 'sales_data_analysis', 'research_docs', 'codebase_inspection')",
    )
    preferred_types: List[str] = Field(
        default_factory=list,
        description="File extensions preferred for this task (e.g. ['csv', 'xlsx'])",
    )
    search_scope: str = Field(
        default="authorized_workspace",
        description="Scope of search, restricted strictly to authorized roots",
    )
    query_terms: List[str] = Field(
        default_factory=list,
        description="Extracted keywords and domain terms to guide search and ranking",
    )
    intent_keywords: List[str] = Field(
        default_factory=list,
        description="Action intents (e.g. 'analyze', 'fix', 'summarize', 'build_website')",
    )


class DiscoveryRequest(BaseModel):
    """Request to discover relevant files within authorized workspace roots."""

    goal: str = Field(..., description="The user's high-level task or objective")
    task_context: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional context such as active plugins, timestamps, or constraints",
    )
    workspace_root_id: Optional[str] = Field(
        default=None,
        description="Target root ID if scoped to a specific root, otherwise all active roots",
    )
    preferred_types: Optional[List[str]] = Field(
        default=None,
        description="Target extensions (e.g. ['csv', 'xlsx', 'py', 'pdf'])",
    )
    max_candidates: int = Field(default=10, ge=1, le=50, description="Maximum candidates to return")
    search_terms: Optional[List[str]] = Field(
        default=None,
        description="Specific search terms or tokens extracted from goal",
    )
    min_score_threshold: float = Field(
        default=0.35,
        ge=0.0,
        le=1.0,
        description="Minimum score threshold for a candidate to be considered relevant",
    )


class CandidateFile(BaseModel):
    """A workspace file identified and scored as a candidate for a task."""

    file_id: str = Field(..., description="Unique candidate file identifier")
    relative_path: str = Field(..., description="Safe relative path within the authorized root")
    absolute_path: Path = Field(..., description="Canonical path on filesystem")
    file_type: str = Field(..., description="Extension or format (e.g. 'csv', 'py', 'pdf')")
    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Relevance score in [0.0, 1.0] derived from multi-signal ranking",
    )
    reason: str = Field(
        ...,
        description="Safe, non-hallucinatory explanation of why this file was selected",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="File metadata (size, timestamps, MIME, categories)",
    )
    scanned_meta: Optional[ScannedFileMetadata] = Field(
        default=None,
        description="Underlying scan metadata if available",
    )

    model_config = {"arbitrary_types_allowed": True}


class DiscoveryResult(BaseModel):
    """Result of task-driven workspace file discovery."""

    candidates: List[CandidateFile] = Field(
        default_factory=list,
        description="All scored candidate files above the minimum threshold, ordered by score descending",
    )
    selected_candidates: List[CandidateFile] = Field(
        default_factory=list,
        description="The candidate(s) automatically chosen when unambiguous",
    )
    ambiguity_detected: bool = Field(
        default=False,
        description="True if multiple candidates share nearly identical high relevance",
    )
    clarification_message: Optional[str] = Field(
        default=None,
        description="Safe clarification question for the user if ambiguous or missing",
    )
    total_files_scanned: int = Field(default=0, ge=0, description="Count of files evaluated")
    duration_ms: float = Field(default=0.0, description="Discovery latency in milliseconds")


class RetrievedContent(BaseModel):
    """Safely retrieved and parsed content for a selected candidate file."""

    file_id: str = Field(..., description="Associated candidate file ID")
    path: str = Field(..., description="Safe relative path")
    content: Optional[str] = Field(
        default=None,
        description="Sanitized text content with credentials redacted (None for binary files)",
    )
    is_binary: bool = Field(default=False, description="Whether the file was detected as binary")
    file_type: str = Field(default="txt", description="Normalized file type")
    size_bytes: int = Field(default=0, ge=0, description="Total size in bytes")
    chunks: List[str] = Field(
        default_factory=list,
        description="Segmented text chunks for large files or RAG ingestion",
    )
    parsed_preview: Optional[Any] = Field(
        default=None,
        description="Structured representation (e.g. row list for CSV/table, dict for JSON)",
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Retrieval metadata")


class WorkspaceContext(BaseModel):
    """Structured workspace context maintained during a task session."""

    authorized_roots: List[WorkspaceRoot] = Field(
        default_factory=list,
        description="Active authorized workspace roots",
    )
    discovered_candidates: List[CandidateFile] = Field(
        default_factory=list,
        description="Candidates discovered for the current goal",
    )
    selected_resources: List[CandidateFile] = Field(
        default_factory=list,
        description="Resources chosen for execution",
    )
    retrieval_status: Dict[str, str] = Field(
        default_factory=dict,
        description="Status of retrieved files by path/ID",
    )
    permissions: Dict[str, PermissionMode] = Field(
        default_factory=dict,
        description="Effective permissions by root_id",
    )
    task_relationship: str = Field(
        default="",
        description="Summary of how selected resources relate to the user goal",
    )
    ambiguity_detected: bool = Field(default=False, description="Whether user input is needed")
    clarification_message: Optional[str] = Field(
        default=None,
        description="Clarification prompt for user if ambiguous or missing",
    )

    model_config = {"arbitrary_types_allowed": True}


__all__ = [
    "PermissionMode",
    "FileCategory",
    "WorkspaceRoot",
    "ScannedFileMetadata",
    "WorkspaceRequirement",
    "DiscoveryRequest",
    "CandidateFile",
    "DiscoveryResult",
    "RetrievedContent",
    "WorkspaceContext",
]
