"""Pydantic schemas and typed definitions for the Xeren Conversation Plugin."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ConversationIntent(str, Enum):
    """Classified communicative intent of a user message."""

    GREETING = "greeting"
    CASUAL = "casual"
    THANKS = "thanks"
    GOODBYE = "goodbye"
    EXPLANATION = "explanation"
    FOLLOW_UP = "follow_up"
    CLARIFICATION = "clarification"
    TOOL_REQUIRED = "tool_required"
    UNKNOWN = "unknown"


class ConversationTone(str, Enum):
    """Desired or expressed tone of conversational responses."""

    FRIENDLY = "friendly"
    PROFESSIONAL = "professional"
    CONCISE = "concise"
    RESPECTFUL = "respectful"
    INFORMATIVE = "informative"


class ConversationMessage(BaseModel):
    """A single turn in the conversation history."""

    role: str = Field(
        ...,
        description="Role of the speaker, typically 'user', 'assistant', or 'system'",
    )
    content: str = Field(
        ...,
        description="Raw text content of the message",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the message was sent",
    )

    model_config = {"arbitrary_types_allowed": True}


class RoutingSignal(BaseModel):
    """Signal indicating whether the user message requires tool or plugin execution."""

    requires_tool: bool = Field(
        default=False,
        description="Whether this user request implies tool or plugin execution",
    )
    suggested_plugin: Optional[str] = Field(
        default=None,
        description="Recommended plugin to handle the task (e.g. 'research', 'coding', 'website')",
    )
    reason: Optional[str] = Field(
        default=None,
        description="Explanation of why this tool/plugin is recommended",
    )
    suggested_action: Optional[str] = Field(
        default=None,
        description="Specific recommended action or operation within the target plugin",
    )


class ConversationInput(BaseModel):
    """Input payload for conversational interaction with Xeren."""

    message: str = Field(
        ...,
        description="User message text",
    )
    context: List[ConversationMessage] = Field(
        default_factory=list,
        description="Recent conversational history turns for context preservation",
    )
    tone: ConversationTone = Field(
        default=ConversationTone.FRIENDLY,
        description="Desired style and tone of the response",
    )
    user_name: Optional[str] = Field(
        default=None,
        description="Optional user name for personalization",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Unique session identifier for tracing conversation threads",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Custom contextual metadata",
    )

    model_config = {"arbitrary_types_allowed": True}


class ConversationResult(BaseModel):
    """Structured response payload generated by the Conversation Plugin."""

    response: str = Field(
        ...,
        description="Natural, respectful conversational response",
    )
    intent: ConversationIntent = Field(
        default=ConversationIntent.UNKNOWN,
        description="Classified user intent",
    )
    routing: RoutingSignal = Field(
        default_factory=RoutingSignal,
        description="Routing signal when tool/plugin execution is required",
    )
    tone_used: ConversationTone = Field(
        default=ConversationTone.FRIENDLY,
        description="Tone applied to the response",
    )
    context_preserved: bool = Field(
        default=False,
        description="Whether conversation history was considered or referenced",
    )
    clarification_needed: bool = Field(
        default=False,
        description="Whether additional user clarification is requested",
    )
    suggested_follow_ups: List[str] = Field(
        default_factory=list,
        description="Helpful follow-up prompt suggestions for natural conversation flow",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Operational and diagnostic metadata",
    )

    model_config = {"arbitrary_types_allowed": True}


__all__ = [
    "ConversationIntent",
    "ConversationTone",
    "ConversationMessage",
    "RoutingSignal",
    "ConversationInput",
    "ConversationResult",
]
